#!/usr/bin/env python3
"""One-command setup wizard for gmail-digest.

Run this once, on your own machine (it opens a browser), AFTER the irreducible
Google Cloud console steps documented in docs/SETUP.md:
  1. enable the Gmail API,
  2. configure the OAuth consent screen and add yourself as a Test user,
  3. create a "Desktop app" OAuth client and download its client_secret_*.json
     into this folder.

Then: `python setup.py`. The wizard will:
  1. auto-detect client_secret_*.json → read client_id / client_secret,
  2. run the OAuth loopback flow → obtain a refresh token,
  3. write a .env with every value filled in,
  4. self-test: fetch the last 24h (read) and send a test digest (send),
  5. optionally push the secrets to GitHub Actions with `gh` (if installed),
  6. print the next steps for the deployment you choose.

Standard library only; no pip install needed.
"""
import glob
import json
import os
import shutil
import subprocess
import sys

from gmail_common import load_dotenv
from gmail_oauth_setup import OAuthError, run_oauth_flow

HERE = os.path.dirname(os.path.abspath(__file__))
PY = sys.executable or "python3"


def prompt(label, default=None, allow_empty=False):
    suffix = " [{}]".format(default) if default else ""
    while True:
        try:
            val = input("{}{}: ".format(label, suffix)).strip()
        except EOFError:
            val = ""
        if not val and default is not None:
            return default
        if val or allow_empty:
            return val
        print("  (required)")


def yesno(label, default=True):
    d = "Y/n" if default else "y/N"
    try:
        val = input("{} [{}]: ".format(label, d)).strip().lower()
    except EOFError:
        val = ""
    if not val:
        return default
    return val in ("y", "yes")


def find_client_secret():
    """Locate a downloaded client_secret_*.json and extract id/secret."""
    candidates = sorted(glob.glob(os.path.join(HERE, "client_secret_*.json")))
    candidates += sorted(glob.glob(os.path.join(HERE, "client_secret.json")))
    for path in candidates:
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, ValueError):
            continue
        # Desktop/web clients nest under "installed" or "web".
        node = data.get("installed") or data.get("web") or data
        cid = node.get("client_id")
        csecret = node.get("client_secret")
        if cid and csecret:
            print("Detected OAuth client in {}".format(os.path.basename(path)))
            return cid, csecret
    return None, None


def write_env(values):
    path = os.path.join(HERE, ".env")
    if os.path.exists(path):
        if not yesno(".env already exists — overwrite?", default=False):
            print("Keeping existing .env (values not written).")
            return path
    lines = ["# Generated by setup.py — DO NOT commit. See .env.example for docs.\n"]
    for key, val in values.items():
        if val is None or val == "":
            continue
        lines.append("{}={}\n".format(key, val))
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    os.environ.update({k: v for k, v in values.items() if v})
    print("Wrote .env")
    return path


def run(cmd, **kw):
    """Run a subprocess, returning (returncode, stdout, stderr)."""
    env = dict(os.environ)
    env.setdefault("PYTHONUTF8", "1")
    try:
        proc = subprocess.run(cmd, cwd=HERE, env=env, capture_output=True,
                              text=True, encoding="utf-8", **kw)
    except OSError as e:
        return 1, "", str(e)
    return proc.returncode, proc.stdout, proc.stderr


def self_test(values):
    print("\n--- Self-test: fetching last 24h (read-only) ---")
    rc, out, err = run([PY, "fetch_inbox.py", "--hours", "24", "--max", "5"])
    if rc != 0:
        print("  FETCH FAILED:\n" + (err or out))
        return False
    try:
        msgs = json.loads(out)
        n = len(msgs)
    except ValueError:
        n = "?"
    print("  OK: fetched {} message(s).".format(n))

    if not yesno("Send a test digest email now?", default=True):
        return True
    print("--- Self-test: sending a test digest ---")
    sample = os.path.join(HERE, "_setup_test_digest.md")
    with open(sample, "w", encoding="utf-8") as f:
        f.write("gmail-digest setup test — if you received this, sending works.\n")
    try:
        rc, out, err = run([PY, "send_digest.py", sample,
                            "--subject", "gmail-digest setup test"])
    finally:
        try:
            os.remove(sample)
        except OSError:
            pass
    if rc != 0:
        print("  SEND FAILED:\n" + (err or out))
        return False
    print("  " + (out.strip() or "OK: sent."))
    return True


def gh_push_secrets(values):
    if not shutil.which("gh"):
        print("`gh` not found — skip (set the 5 secrets manually; see docs/SETUP.md).")
        return
    if not yesno("Push secrets to GitHub Actions with `gh secret set`?", default=False):
        return
    repo = prompt("  GitHub repo (owner/name, blank = current dir's remote)",
                  default="", allow_empty=True)
    secret_keys = ["GMAIL_CLIENT_ID", "GMAIL_CLIENT_SECRET", "GMAIL_REFRESH_TOKEN",
                   "GMAIL_USER", "ANTHROPIC_API_KEY"]
    for key in secret_keys:
        val = values.get(key)
        if not val:
            print("  skip {} (no value)".format(key))
            continue
        cmd = ["gh", "secret", "set", key, "--body", val]
        if repo:
            cmd += ["--repo", repo]
        rc, out, err = run(cmd)
        print("  {} {}".format("OK " if rc == 0 else "FAIL", key)
              + ("" if rc == 0 else ": " + (err or out).strip()))
    # Optional extra config as repository variables.
    for key in ("ANTHROPIC_MODEL", "DIGEST_TO", "DIGEST_HOURS"):
        val = values.get(key)
        if not val:
            continue
        cmd = ["gh", "variable", "set", key, "--body", val]
        if repo:
            cmd += ["--repo", repo]
        run(cmd)


def print_next_steps(choice):
    print("\n==================  NEXT STEPS  ==================")
    if choice == "1":
        print(
            "GitHub Actions + Anthropic API:\n"
            "  1. Commit & push this repo to GitHub.\n"
            "  2. Ensure these secrets exist (the wizard can set them, or do it in\n"
            "     Settings > Secrets and variables > Actions):\n"
            "       GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN,\n"
            "       GMAIL_USER, ANTHROPIC_API_KEY\n"
            "  3. Edit the cron in .github/workflows/daily-digest.yml (UTC!).\n"
            "  4. Actions tab > Daily Email Digest > Run workflow to test.\n"
            "  See docs/SETUP.md section 3a.")
    elif choice == "2":
        print(
            "Claude Code routine (no API key needed):\n"
            "  1. Point Claude Code / claude.ai at this repo.\n"
            "  2. Use /schedule with a prompt that follows ROUTINE.md.\n"
            "  See docs/SETUP.md section 3b.")
    else:
        print(
            "Local cron / Task Scheduler:\n"
            "  - macOS/Linux: run ./run_local.sh (needs ANTHROPIC_API_KEY in .env),\n"
            "    then add a crontab entry.\n"
            "  - Windows: run run_local.ps1, then add a Task Scheduler task.\n"
            "  See docs/SETUP.md section 3c.")
    print("\nThen: configure phone notifications (docs/NOTIFICATIONS.md) and\n"
          "customize ROUTINE.md to your own filtering/summary rules.")
    print("=================================================")


def main():
    load_dotenv()
    print("=== gmail-digest setup wizard ===\n")

    # 1. OAuth client id/secret.
    cid, csecret = find_client_secret()
    if not cid:
        print("No client_secret_*.json found in this folder.")
        cid = os.environ.get("GMAIL_CLIENT_ID") or prompt("OAuth client ID")
        csecret = os.environ.get("GMAIL_CLIENT_SECRET") or prompt("OAuth client secret")

    # 2. OAuth loopback → refresh token.
    print("\n--- Authorizing with Google (a browser window will open) ---")
    try:
        refresh = run_oauth_flow(cid, csecret)
    except OAuthError as e:
        sys.stderr.write("ERROR: " + str(e) + "\n")
        sys.exit(1)
    print("Got refresh token.")

    # 3. Remaining config.
    print()
    user = os.environ.get("GMAIL_USER") or prompt("Your Gmail address (GMAIL_USER)")
    anthropic_key = prompt(
        "Anthropic API key (ANTHROPIC_API_KEY) — needed for GitHub Actions / local; "
        "leave blank for the Claude Code routine path",
        default=os.environ.get("ANTHROPIC_API_KEY", ""), allow_empty=True)
    model = prompt("Anthropic model (ANTHROPIC_MODEL)",
                   default=os.environ.get("ANTHROPIC_MODEL", "claude-haiku-4-5"))
    digest_to = prompt("Digest recipient (DIGEST_TO) — blank = <user>+digest alias",
                       default=os.environ.get("DIGEST_TO", ""), allow_empty=True)
    digest_hours = prompt("Look-back window in hours (DIGEST_HOURS)",
                          default=os.environ.get("DIGEST_HOURS", "24"))

    values = {
        "GMAIL_CLIENT_ID": cid,
        "GMAIL_CLIENT_SECRET": csecret,
        "GMAIL_REFRESH_TOKEN": refresh,
        "GMAIL_USER": user,
        "ANTHROPIC_API_KEY": anthropic_key,
        "ANTHROPIC_MODEL": model,
        "DIGEST_TO": digest_to,
        "DIGEST_HOURS": digest_hours,
    }

    # 4. Write .env + self-test.
    write_env(values)
    self_test(values)

    # 5. Deployment choice + optional gh secret push.
    print("\nWhich deployment do you want?")
    print("  1) GitHub Actions + Anthropic API (primary)")
    print("  2) Claude Code routine")
    print("  3) Local cron / Task Scheduler")
    choice = prompt("Choice", default="1")
    if choice == "1":
        gh_push_secrets(values)
    print_next_steps(choice)
    print("\nDone.")


if __name__ == "__main__":
    main()
